### ISSUE TITLE
Refactor HelperFunction

### ISSUE THREAD

**Issue by aversey** [DD2480-group14/Assignment-1#41]
The code as it is contains a lot of duplications and is quite unclear. Maybe it is a good idea to provide a separate class for planar Point.

**Comment by aversey** [comment]
I think it is reasonable to create Point class with methods `double norm()`, `double circleRadius(Point b, Point c)`, `double triangleArea(Point b, Point c)`, `double angle(Point a, Point c)`, `Point crossProduct(Point b)`, `Point subtract(Point b)`.

Distance is then expressed as:
```
this.subtract(b).norm()
```
Triangle area can be expressed as (this is slower than current algorithm, but a bit more clear -- current algorithm uses determinant of 3×3 matrix):
```
b = b.subtract(this);
c = c.subtract(this);
b.crossProduct(c).norm() / 2.0
```
Angle can be expressed as:
```
a = a.subtract(this);
c = c.subtract(this);
Math.asin(a.crossProduct(c).norm() / a.norm() / c.norm())
```
I don't know yet how to express circleRadius nicely.

**Comment by aversey** [comment]
Maybe the class should be Complex instead of Point.

**Comment by dengty1998** [comment]
I agree with refactoring this function because I found there could be something wrong in _checkAngle_. In [decide](https://canvas.kth.se/courses/37918/files/6157550/download), it mentioned that "the second of the three consecutive points is always the vertex of the angle". But it seems we calculate all angles.
